flowchart TD
    wup__cli["wup.cli<br/>6 funcs"]
    wup__config["wup.config<br/>5 funcs"]
    wup__core["wup.core<br/>24 funcs"]
    wup__testql_watcher["wup.testql_watcher<br/>18 funcs"]
    wup__cli ==>|4| wup__config
    wup__testql_watcher -->|1| wup__config
    wup__core -->|1| wup__config
