flowchart TD
%% generated in 0.01s

    %% Entry points (blue)
    classDef entry fill:#4dabf7,stroke:#1971c2,color:#fff

    subgraph CLI
        wup__testql_cli_generator__TestQLCLIGenerator__generate["generate"]
        wup__testql_cli_generator__TestQLCLIGenerator___generate_smoke_scenario["_generate_smoke_scenario"]
        wup__testql_cli_generator__TestQLCLIGenerator___generate_command_scenario["_generate_command_scenario"]
        wup__testql_cli_generator__TestQLCLIGenerator__generate_custom_scenario["generate_custom_scenario"]
        wup__testql_cli_generator__TestQLCLIGenerator__print_summary["print_summary"]
        wup__cli___load_watch_config["_load_watch_config"]
        wup__cli___print_watch_header["_print_watch_header"]
        wup__cli___refresh_monitoring_manifest["_refresh_monitoring_manifest"]
        wup__cli___create_watcher["_create_watcher"]
        wup__cli__watch["watch"]
        wup__cli___auto_generate_config["_auto_generate_config"]
        wup__cli__map_deps["map_deps"]
        wup__cli__status["status"]
        wup__cli__init["init"]
        wup__cli__testql_endpoints["testql_endpoints"]
        ...["+29 more"]
    end

    subgraph Core
        wup__monitoring_manifest___parse_port_mapping["_parse_port_mapping"]
        wup__monitoring_manifest___extract_service_from_spec["_extract_service_from_spec"]
        wup__monitoring_manifest__discover_docker_compose_services["discover_docker_compose_servic"]
        wup__monitoring_manifest___host_port_from_mapping["_host_port_from_mapping"]
        wup__monitoring_manifest__build_monitoring_manifest("build_monitoring_manifest CC=9")
        wup___base_detector__BaseDetector__detect["detect"]
        wup__anomaly_detector__AnomalyDetector___should_scan["_should_scan"]
        wup__anomaly_detector__AnomalyDetector__scan_file["scan_file"]
        wup__anomaly_detector__AnomalyDetector__scan_directory["scan_directory"]
        wup__anomaly_detector__AnomalyDetector__get_summary["get_summary"]
        wup__anomaly_detector__AnomalyDetector__print_report["print_report"]
        wup__anomaly_detector__quick_scan["quick_scan"]
        wup__anomaly_detector__scan_yaml_changes["scan_yaml_changes"]
        wup__testql_monitor__ProbeTarget__probe["probe"]
        wup__testql_monitor___ProbeAccumulator__add["add"]
        ...["+164 more"]
    end

    class wup__testql_cli_generator__TestQLCLIGenerator__generate,wup__testql_cli_generator__TestQLCLIGenerator___generate_smoke_scenario,wup__testql_cli_generator__TestQLCLIGenerator___generate_command_scenario,wup__testql_cli_generator__TestQLCLIGenerator__generate_custom_scenario,wup__testql_cli_generator__TestQLCLIGenerator__print_summary,wup__monitoring_manifest___host_port_from_mapping,wup___base_detector__BaseDetector__detect,wup__anomaly_detector__AnomalyDetector___should_scan,wup__anomaly_detector__AnomalyDetector__scan_file,wup__anomaly_detector__AnomalyDetector__scan_directory entry
