flowchart TD
%% generated in 0.07s

    %% Entry points (blue)
    classDef entry fill:#4dabf7,stroke:#1971c2,color:#fff

    subgraph CLI
        packages__cli2wup__src__cli2wup__cli__run_shell["run_shell"]
        packages__cli2wup__src__cli2wup__cli__main["main"]
        wup__testql_cli_generator__TestQLCLIGenerator__generate["generate"]
        wup__testql_cli_generator__TestQLCLIGenerator___generate_smoke_scenario["_generate_smoke_scenario"]
        wup__testql_cli_generator__TestQLCLIGenerator___generate_command_scenario["_generate_command_scenario"]
        wup__testql_cli_generator__TestQLCLIGenerator__generate_custom_scenario["generate_custom_scenario"]
        wup__testql_cli_generator__TestQLCLIGenerator__print_summary["print_summary"]
        wup__cli_bridge___fail["_fail"]
        wup__cli_bridge__run_map_deps["run_map_deps"]
        wup__cli_bridge__run_init["run_init"]
        wup__cli_bridge__run_sync["run_sync"]
        wup__cli_bridge__run_generate["run_generate"]
        wup__cli_bridge__run_validate["run_validate"]
        wup__cli_bridge__run_status["run_status"]
        wup__cli_bridge__run_endpoints["run_endpoints"]
        ...["+50 more"]
    end

    subgraph Core
        packages__rest2wup__src__rest2wup__cli__main["main"]
        packages__uri2wup__src__uri2wup__cli__main["main"]
        packages__uri2wup__src__uri2wup__nlp2uri__UriHit__to_dict["to_dict"]
        packages__uri2wup__src__uri2wup__query__QueryResult__to_dict["to_dict"]
        packages__uri2wup__src__uri2wup__query__query_uri{{query_uri CC=23}}
        packages__uri2wup__src__uri2wup__decode__decode_uri{{decode_uri CC=20}}
        packages__uri2wup__src__uri2wup__uri__uri_for_cmd["uri_for_cmd"]
        packages__uri2wup__src__uri2wup__patch__PatchResult__to_dict["to_dict"]
        packages__uri2wup__src__uri2wup__patch__patch_uri{{patch_uri CC=17}}
        packages__nlp2wup__src__nlp2wup__cli__main["main"]
        packages__nlp2wup__src__nlp2wup__validate__validate_wup_config["validate_wup_config"]
        packages__nlp2wup__src__nlp2wup__generate__generate_from_nl["generate_from_nl"]
        packages__nlp2wup__src__nlp2wup__apply__ApplyResult__to_dict["to_dict"]
        packages__nlp2wup__src__nlp2wup__apply___intent{{_intent CC=21}}
        packages__nlp2wup__src__nlp2wup__apply__to_dsl{{to_dsl CC=24}}
        ...["+238 more"]
    end

    class packages__cli2wup__src__cli2wup__cli__run_shell,packages__cli2wup__src__cli2wup__cli__main,packages__rest2wup__src__rest2wup__cli__main,packages__uri2wup__src__uri2wup__cli__main,packages__uri2wup__src__uri2wup__nlp2uri__UriHit__to_dict,packages__uri2wup__src__uri2wup__query__QueryResult__to_dict,packages__uri2wup__src__uri2wup__uri__uri_for_cmd,packages__uri2wup__src__uri2wup__patch__PatchResult__to_dict,packages__nlp2wup__src__nlp2wup__cli__main,packages__nlp2wup__src__nlp2wup__validate__validate_wup_config entry
