"""Generate Pydantic models from JSON schemas."""

from __future__ import annotations

import json
from pathlib import Path


def generate_models() -> str:
    schema_dir = Path(__file__).parent / "schema" / "commands"
    
    lines = [
        '# This file is auto-generated by dsl2wup.codegen. Do not edit manually.',
        'from __future__ import annotations',
        '',
        'from typing import Literal, Optional',
        'from pydantic import BaseModel, ConfigDict',
        '',
    ]
    
    # Sort schemas by name to get a deterministic output
    schema_files = sorted(schema_dir.glob("*.schema.json"))
    
    model_entries: list[tuple[str, str]] = []

    for f in schema_files:
        verb_key = f.name.replace(".schema.json", "").upper()
        stem = f.name.replace(".schema.json", "")
        class_name = "".join(part.capitalize() for part in stem.split("_")) + "Command"
        model_entries.append((verb_key, class_name))
        
        schema = json.loads(f.read_text(encoding="utf-8"))
        required = set(schema.get("required", []))
        properties = schema.get("properties", {})
        
        lines.append(f"class {class_name}(BaseModel):")
        lines.append("    model_config = ConfigDict(extra=\"forbid\")")
        lines.append("")
        
        for name, prop in properties.items():
            # Handle verb
            if name == "verb":
                if "const" in prop:
                    const_val = prop["const"]
                    lines.append(f"    verb: Literal[{const_val!r}] = {const_val!r}")
                elif "enum" in prop:
                    vals = ", ".join(repr(v) for v in prop["enum"])
                    # Default to the first one for Pydantic field
                    default_val = prop["enum"][0]
                    lines.append(f"    verb: Literal[{vals}] = {default_val!r}")
                continue
            
            # Type detection
            json_type = prop.get("type", "string")
            type_map = {"string": "str", "integer": "int", "boolean": "bool"}
            py_type = type_map.get(json_type, "str")
            if "enum" in prop:
                vals = ", ".join(repr(v) for v in prop["enum"])
                py_type = f"Literal[{vals}]"
            
            # Default value detection
            has_default = "default" in prop
            default_val = prop.get("default")
            
            is_required = name in required
            
            default_repr = repr(default_val) if json_type != "boolean" else repr(bool(default_val))
            if is_required:
                if has_default:
                    lines.append(f"    {name}: {py_type} = {default_repr}")
                else:
                    lines.append(f"    {name}: {py_type}")
            else:
                if has_default:
                    lines.append(f"    {name}: {py_type} = {default_repr}")
                else:
                    lines.append(f"    {name}: Optional[{py_type}] = None")
        lines.append("")
        
    lines.append("")
    lines.append("WUP_COMMAND_MODELS = {")
    for verb_key, class_name in model_entries:
        lines.append(f"    {verb_key!r}: {class_name},")
    lines.append("}")
    lines.append("")
    
    return "\n".join(lines)


def main() -> None:
    output_file = Path(__file__).parent / "models.py"
    code = generate_models()
    output_file.write_text(code, encoding="utf-8")
    print(f"Generated Pydantic models → {output_file}")


if __name__ == "__main__":
    main()
