"""Generate Pydantic models from JSON schemas."""

from __future__ import annotations

import json
from pathlib import Path


_HEADER = [
    '# This file is auto-generated by dsl2wup.codegen. Do not edit manually.',
    'from __future__ import annotations', '', 'from typing import Literal, Optional',
    'from pydantic import BaseModel, ConfigDict', '',
]


def _field_type(prop: dict[str, object]) -> str:
    if values := prop.get("enum"):
        return f"Literal[{', '.join(repr(value) for value in values)}]"
    return {"string": "str", "integer": "int", "boolean": "bool"}.get(prop.get("type", "string"), "str")


def _field_line(name: str, prop: dict[str, object], required: set[str]) -> str | None:
    if name == "verb":
        values = [prop["const"]] if "const" in prop else prop.get("enum", [])
        return f"    verb: Literal[{', '.join(repr(value) for value in values)}] = {values[0]!r}" if values else None
    field_type = _field_type(prop)
    has_default = "default" in prop
    default = bool(prop["default"]) if prop.get("type") == "boolean" and has_default else prop.get("default")
    if name not in required and not has_default:
        return f"    {name}: Optional[{field_type}] = None"
    suffix = f" = {default!r}" if has_default else ""
    return f"    {name}: {field_type}{suffix}"


def _append_model(lines: list[str], schema_file: Path) -> tuple[str, str]:
    stem = schema_file.name.removesuffix(".schema.json")
    entry = (stem.upper(), "".join(part.capitalize() for part in stem.split("_")) + "Command")
    schema = json.loads(schema_file.read_text(encoding="utf-8"))
    required = set(schema.get("required", []))
    lines.extend((f"class {entry[1]}(BaseModel):", '    model_config = ConfigDict(extra="forbid")', ""))
    for name, prop in schema.get("properties", {}).items():
        if line := _field_line(name, prop, required):
            lines.append(line)
    lines.append("")
    return entry


def generate_models() -> str:
    schema_dir = Path(__file__).parent / "schema" / "commands"
    lines = list(_HEADER)
    model_entries = [_append_model(lines, schema_file) for schema_file in sorted(schema_dir.glob("*.schema.json"))]
    lines.append("")
    lines.append("WUP_COMMAND_MODELS = {")
    for verb_key, class_name in model_entries:
        lines.append(f"    {verb_key!r}: {class_name},")
    lines.append("}")
    lines.append("")
    
    return "\n".join(lines)


def main() -> None:
    output_file = Path(__file__).parent / "models.py"
    code = generate_models()
    output_file.write_text(code, encoding="utf-8")
    print(f"Generated Pydantic models → {output_file}")


if __name__ == "__main__":
    main()
