# This file is auto-generated by dsl2wup.codegen. Do not edit manually.
from __future__ import annotations

from typing import Literal, Optional
from pydantic import BaseModel, ConfigDict

class AdoptCommand(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verb: Literal['ADOPT'] = 'ADOPT'
    root: str = '.'
    out: Optional[str] = None

class EndpointsCommand(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verb: Literal['ENDPOINTS'] = 'ENDPOINTS'
    scenarios_dir: str
    out: str = 'testql-deps.json'
    testql_bin: str = 'testql'

class GenerateCommand(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verb: Literal['GENERATE'] = 'GENERATE'
    text: Optional[str] = None
    out: Optional[str] = None
    project: Optional[str] = None
    template: Optional[Literal['fastapi', 'flask', 'django', 'express']] = None

class HealthCommand(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verb: Literal['HEALTH'] = 'HEALTH'
    service: Optional[str] = None
    project: Optional[str] = None

class InitCommand(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verb: Literal['INIT'] = 'INIT'
    project: str = '.'
    out: str = 'wup.yaml'

class InitCliCommand(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verb: Literal['INIT_CLI'] = 'INIT_CLI'
    project: str = '.'
    out: str = 'wup.yaml'
    scenarios: str = 'testql-scenarios'
    merge: bool = False
    infer_args: bool = True

class MapCommand(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verb: Literal['MAP'] = 'MAP'
    project: str = '.'
    out: str = 'deps.json'
    framework: str = 'auto'

class PatchCommand(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verb: Literal['PATCH', 'UPDATE', 'REPLACE'] = 'PATCH'
    target: str
    with_path: str
    file: Optional[str] = None
    project: Optional[str] = None

class QueryCommand(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verb: Literal['QUERY'] = 'QUERY'
    target: str
    file: Optional[str] = None
    format: Literal['json', 'yaml', 'less'] = 'json'
    project: Optional[str] = None

class ResolveCommand(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verb: Literal['RESOLVE'] = 'RESOLVE'
    text: str
    file: Optional[str] = None
    project: Optional[str] = None

class StatusCommand(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verb: Literal['STATUS'] = 'STATUS'
    project: str = '.'
    deps_file: str = 'deps.json'
    file: Optional[str] = None
    delta_seconds: int = 0
    failed_only: bool = False

class SyncCommand(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verb: Literal['SYNC'] = 'SYNC'
    project: str = '.'
    file: Optional[str] = None
    merge_endpoints: bool = False

class ValidateCommand(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verb: Literal['VALIDATE'] = 'VALIDATE'
    path: Optional[str] = None
    project: Optional[str] = None


WUP_COMMAND_MODELS = {
    'ADOPT': AdoptCommand,
    'ENDPOINTS': EndpointsCommand,
    'GENERATE': GenerateCommand,
    'HEALTH': HealthCommand,
    'INIT': InitCommand,
    'INIT_CLI': InitCliCommand,
    'MAP': MapCommand,
    'PATCH': PatchCommand,
    'QUERY': QueryCommand,
    'RESOLVE': ResolveCommand,
    'STATUS': StatusCommand,
    'SYNC': SyncCommand,
    'VALIDATE': ValidateCommand,
}
